<h2 id="исправление-ошибок">Fixes</h2>

<p><a href="https://help.loginom.ru/adminguide/server/" target="_blank"><strong>Loginom Server:</strong></a> The error that occurred in the <a href="https://help.loginom.ru/userguide/admin/dispatcher.html" target="_blank">Session Manager</a> while attempting to stop the package execution in the session created from <a href="https://help.loginom.ru/userguide/workflow/batchlauncher.html" target="_blank">BatchLauncher</a> was corrected. After clicking on "Stop" button the following message was displayed: "Null reference to object". But the package was still being executed. The package execution stopps after introduced corrections, no errors occur (#10110).</p>

<p><strong>Loginom Server:</strong> The old session identifier was displayed in the <em>Session Manager</em> after its restart. Namely, the identifier of the session and the date of its creation didn't change. The error occurred when starting specially prepared workflows. Under normal conditions of the product use the error was not reproduced. Corrections were introduced (#10111).</p>

<p><strong>Loginom Server:</strong> In the case of the multiple sequential starts of batch processing in the <em>Session Manager</em> for the sessions created from BatchLauncher, sometimes "Deleted" was incorrectly displayed in <em>Activity</em> column during the package execution. The error could occur when starting specially prepared workflows. Under normal conditions of the product use the error was not reproduced. Error of behavior was corrected (#10112).</p>

<p><a href="https://help.loginom.ru/userguide/processors/programming/python/" target="_blank"><strong>Python:</strong></a> When using Python 3.9.x, start of scripts inside the Loginom process caused "Access violation" error. It appeared in version 7.0.0. The required corrections were introduced (#10065).</p>

<p><a href="https://help.loginom.ru/userguide/processors/datamining/association-rules.html" target="_blank"><strong>Association rules:</strong></a> "Access violation" regression error was corrected. It appeared in version 7.0.0 and it occurred if the user stopped the node training process, entered the wizard, changed any parameter, saved the settings and started the node retraining (#10067).</p>

<p><strong>Association rules:</strong> If "Out of memory" error occurred when training the node, after settings changing and repeated node training the output port remained empty, and while attempting to execute the node, a message appeared with information that the node was not trained. It was impossible to train other <em>Association rules</em> nodes in the current workflow using the same data. It is a regression error and it appeared in version 7.0.0. Corrections were introduced (#10069).</p>

<p><strong>Association rules:</strong> Not all rules satisfying minimum reliability could be selected because of the rounding error. The error was corrected. The rules were checked for the minimum reliability with the accuracy up to the whole percentage (#10091).</p>

<p><strong>Association rules:</strong> "Access violation" error was corrected. It occurred if large data sets were supplied to both node inputs, nodes were configured (elements and transactions were set) and then the node training process was started and terminated (#10094).</p>

<p><a href="https://help.loginom.ru/userguide/visualization/data-quality/" target="_blank"><strong>Data quality visualizer:</strong></a> The following error was corrected: "Cannot read properties of undefined (reading 'isGroupHeader')". It occurred when activating <em>Data quality</em> visualizer from the <em>Reports</em> page without prior entering the visualizer from the&nbsp;<em>Visualizers</em> page (#9470).</p>

<p><a href="https://help.loginom.ru/userguide/visualization/table/" target="_blank"><strong>Table visualizer:</strong></a> The following error was corrected: "Data set is not in the closed state". It occurred if the user set the sorting by ~20 columns in the table with many columns (~200), quickly went to the workflow opened in the next tab and deactivated the node on which the visualizer was configured (#9963).</p>

<p><strong>Table visualizer:</strong> Auto selection of the column width by the header text didn't work for some columns due to rounding and difference in 1 pixel. The problem is typical of some browsers (for example, Chrome). Corrections were introduced.</p>

<p><a href="https://help.loginom.ru/userguide/processors/transformation/grouping.html" target="_blank"><strong>Grouping</strong></a>, <a href="https://help.loginom.ru/userguide/processors/variables/variables-from-table.html" target="_blank"><strong>Table to variables:</strong></a> For the columns that relate to the integer type and contain the values that are more than 2<sup>53</sup> - 1 or less than -2<sup>53</sup> + 1, errors can occur in aggregations: <em>Minimum, Maximum, Mode, First, Last, Single</em>. When calculating the unique values count, different unique values could be counted as one. The required corrections were introduced, indicators are calculated without loss of accuracy (#9943).</p>

<p><a href="https://help.loginom.ru/userguide/integration/import/ldf.html" target="_blank"><strong>Import from LGD:</strong></a> If the output fields were deleted for the data set with one column in the output port, the field related to the<em>Variable</em> type was added and they were connected afterwards, the following error occurred when starting the node: "Metadata does not comply with the previously declared metadata" (#8426).</p>

<p><strong>Импорт из LGD:</strong>&nbsp;When connecting the fields related to different types with the field related to the <em>Variable</em> type, the following error could occur: "Unsupported Variant subtype" (#8427).</p>

<p><a href="https://help.loginom.ru/userguide/processors/preprocessing/coarse-classes.html" target="_blank"><strong>Coarse сlasses:</strong></a> Opening of the wizard of the <em>Coarse сlasses</em> node in the page browser following the link received using Share button, caused the following error: "When switching to "Coarse classes. Configuration", the error occurred. Cannot read properties of undefined (reading 'PrepareFilterField')". The error was corrected.</p>

<p><strong>Logging:</strong> Screening of the string parameters values was added for the log parts that are recorded in JSON format (parameters). Now the parameters related to the <code>Boolean</code> type instead of <code>True</code> and <code>False</code> are recorded as <code>true</code>and <code>false</code>.</p>

<p><strong>Desktop application:</strong> The following problems were solved: incorrect display of the application window when the desktop Loginom edition with two display monitors was used, namely:</p>

<ul>
	<li>when dragging the application window from one screen (the larger one) to another one, a part of the window was covered with the grey panel (#9024);</li>
	<li>when dragging the application window from the larger screen (~4К) to the smaller one, the window didn't change the scale automatically (#9091);</li>
	<li>if the application was deployed two times to full screen using Win+Up keys on the left screen, a part of the window was displayed on the right screen (when using one screen, a part of the window was under the Taskbar(#8296).</li>
</ul>

<p><strong>Desktop application:</strong> When opening any package (to open using Loginom) or just when starting Loginom CE, the application window was opened but the interface was not displayed. It was possible to close this Loginom CE window only using the Sesson Manager. The repeated application launch was successful. The problem of the first launch was solved (#9720).</p>

<p><a href="https://help.loginom.ru/userguide/processors/datamining/neural-network-classification.html" target="_blank"><strong>Neural network (Classification):</strong></a> "Not trained neural network" error was corrected. It occurred in the <em>Neural network (Classification)</em> node, the layers configuration of which was set using the control variables. The error could occur after repeated opening of the package and activation of the trained neural network, and also if the clone of such neural network was activated (#10137).</p>

<p><strong>Workflow construction area:</strong> After cancellation of the process executed for a long time via <a href="https://help.loginom.ru/userguide/interface/processes-panel.html" target="_blank">Processes Bar</a> (for example, JavaScript node with the loop equal to 100,000,000 iterations), the node activation animation was preserved in the workflow construction area, some interface elements were not available. The error was corrected (#6246).</p>

<p><strong>Workflow construction area:</strong> The cloned node appeared far from the source one if the source node was located far from the left upper corner of the workflow construction area. The further the node was located from the left upper corner of the workflow construction area, the futher the cloned node appeared from it. Error of behavior was corrected (#4908).</p>

<p><strong>Workflow construction area:</strong> If the scale was changed using the "Workflow map" function, the node was added to the workflow construction area in the right lower corner, then the package was saved and closed, and the coordinates of the added node were incorrect after saving the package in 100% scale. The node was located in the lower corner of the visible workflow part. But it was to be located in the same place where it was added when changing the scale. The error of coordinates saving was corrected (#10097).</p>

<p><a href="https://help.loginom.ru/userguide/integration/connections/" target="_blank"><strong>Connection to database:</strong></a> The following error was corrected: "Login failed for user...". It occurred after opening of the package with preset connection to database with the password that contained more than 32 characters when activating or testing the connection. When saving the package, the password was cut up to 32 bytes, and in the result, the connection to database didn't work after the repeated opening of the package (#9462).</p>

<p><strong>Connection to database:</strong> When  database and server connection was lost, start of&nbsp;<em>Import from database</em> node execution was finished with cancellation of the node execution. Namely, the node was not executed, and the user received no messages. The situation was rectified. Upon database server connection loss, <em>Import from database</em> node execution was finished with an error message (#10049).</p>

<p><a href="https://help.loginom.ru/userguide/integration/connections/list/schemes.html" target="_blank"><strong>Connection of XSD schemas set:</strong></a> The following error was corrected: "List index out of bounds". It occurred in <em>Configuration of XSD schemas set</em> wizard when adding two schemas to the list and deleting them one by one (#9522).</p>

<p><a href="https://help.loginom.ru/userguide/processors/control/supernode.html" target="_blank"><strong>Supernode:</strong></a> When adding 5 or more input or output ports to the supernode and selecting the port type, after saving it was not possible to change the type of any of the previously added ports. The error was corrected (#10123).</p>

<p><strong>Application:</strong> The following situation was observed in <em>Table</em>, <a href="https://help.loginom.ru/userguide/interface/property-inspector.html" target="_blank">Property inspector</a> and <em>Session manager</em> visualizers: the cell was not selected in the table after right-clicking, and the context menu displayed the items for the previous selected cell. Error of behavior was corrected (#8104).</p>

<p><strong>Application:</strong> "Cannot read property 'NodeIndex' of null" error was corrected. It occurred if the user with the administration rights only opened the package from the file storage. Now, in this case the explanatory message is displayed (#6787).</p>

<p><strong>Application:</strong> The pop-up tip was not hidden in the wizards for the link for which there was no field. Such a situation could arise, for example, if data was supplied to the second input port in the <em>Binning</em> node, connection was set with the usage type in the wizard for any input field, then the fields or usage types were filtered in such a way that the connected field didn't fall under the filtering criterion (it was hidden). The tip previously displayed for connection was not hidden. Error of behavior was corrected (#9955).</p>

<p><strong>Application:</strong> The first week day and the text of the Current Date button (the button name is Current Date in the Russian and English versions) were not localized in the Date/time value entry editor (for example, it is used in <a href="https://help.loginom.ru/userguide/processors/transformation/row-filter/" target="_blank">Row filter</a> node). The error was corrected (#10096).</p>

<p><strong>"Connections" page:</strong> "Cannot read property 'getStore' of undefined" error was corrected. It occurred if <em>"Connections" page</em> was closed while testing the connection being activated for a long time (#8763).</p>

<p><a href="https://help.loginom.ru/userguide/processors/control/condition.html" target="_blank"><strong>Condition:</strong></a>&nbsp;<em>Move up</em> and <em>Move down</em> buttons were available in the wizard in the absence of ports (if the wizard was opened just after adding the node to the workflow construction area). Error of behavior was corrected. If there is nothing to move, the buttons are not available (#10013).</p>

<p><strong>Condition:</strong> If 2 ports were set on the page of "Configure list of ports" wizard, and then the second port was moved up, the numbering of ports (rows in the table containing the list of ports) was broken. Both ports were numbered 2. The error was corrected (#10014).</p>

<p><a href="https://help.loginom.ru/userguide/integration/export/excel.html" target="_blank"><strong>Export to Excel file:</strong></a> "Sheet name not set" error was corrected. It occurred in the Export to Excel file wizard when using the variable as the value of the <em>Sheet name</em> parameter after clicking on <em>Next</em> button at the first wizard step (#10081).</p>

<p><a href="https://help.loginom.ru/userguide/integration/export/ldf.html" target="_blank"><strong>Export to LGD file:</strong></a> If the node execution was stopped (by pressing the node) while exporting to LGD file for a long time, the node moved to "Successfully executed" state anyway. It is a regression error and it appeared in version 7.0.0. Corrections were introduced: the export node execution of which was terminated remained grey, and it was specified in the <em>Processes bar</em> that processing was terminated (#10028).</p>

<p><strong>Export to LGD file:</strong> When <em>Export</em>&nbsp;was performed from <em>LGD, TXT, Excel import</em> or from <em>Loop</em>, when rearranging the fields that contained null values, the fields were exported incorrectly: false, 0, 0.00, 00:00 or empty rows appeared instead of null values according to the type; null values appeared instead of non-zero values. The error was corrected (#9896).</p>

<p><strong>Export to LGD file:</strong> "Access violation" error was corrected. It occurred when activating the node in the input port of which all fields were deleted with the exception of the field related to the variable type (or the field related to the variable type was moved to another position in the list). In this case, the input data set came from&nbsp;<em>LGD, TXT, Excel import</em> or from <em>Loop</em> nodes (#9612).</p>

<div class="text-align-center">
<p class="lg-text-btn lg-text-btn_border"><a href="https://loginom.ru/download">Try new version</a></p>
</div>
