<h2 id="исправление-ошибок">Fixes</h2>

<p><a href="https://help.loginom.ru/adminguide/server/" target="_blank"><strong>Loginom Server:</strong></a> The error that occurred in the <a href="https://help.loginom.ru/userguide/admin/dispatcher.html" target="_blank">Session Manager</a> while attempting to stop the package execution in the session created from <a href="https://help.loginom.ru/userguide/workflow/batchlauncher.html" target="_blank">BatchLauncher</a> was corrected. After clicking on "Stop" button the following message was displayed: "Null reference to object". But the package was still being executed. The package execution stops after introduced corrections, no errors occur (#10110).</p>

<p><strong>Loginom Server:</strong> The old session identifier was displayed in the <em>Session Manager</em> after its restart. Namely, the identifier of the session and the date of its creation didn't change. The error occurred when starting specially prepared workflows. Under normal conditions of the product use the error was not reproduced. Corrections were introduced (#10111).</p>

<p><strong>Loginom Server:</strong> In the case of the multiple sequential starts of batch processing in the <em>Session Manager</em> for the sessions created from BatchLauncher, sometimes "Deleted" was incorrectly displayed in <em>Activity</em> column during the package execution. The error could occur when starting specially prepared workflows. Under normal conditions of the product use the error was not reproduced. Error of behavior was corrected (#10112).</p>

<p><a href="https://help.loginom.ru/userguide/processors/programming/python/" target="_blank"><strong>Python:</strong></a> When using Python 3.9.x, start of scripts inside the Loginom process caused "Access violation" error. It appeared in version 7.0.0. The required corrections were introduced (#10065).</p>

<p><a href="https://help.loginom.ru/userguide/processors/datamining/association-rules.html" target="_blank"><strong>Association rules:</strong></a> "Access violation" regression error was corrected. It appeared in version 7.0.0 and it occurred if the user stopped the node training process, entered the wizard, changed any parameter, saved the settings and started the node retraining (#10067).</p>

<p><strong>Association rules:</strong> If "Out of memory" error occurred when training the node, after settings changing and repeated node training the output port remained empty, and while attempting to execute the node, a message appeared with information that the node was not trained. It was impossible to train other <em>Association rules</em> nodes in the current workflow using the same data. It is a regression error and it appeared in version 7.0.0. Corrections were introduced (#10069).</p>

<p><strong>Association rules:</strong> Not all rules satisfying minimum reliability could be selected because of the rounding error. The error was corrected. The rules were checked for the minimum reliability with the accuracy up to the whole percentage (#10091).</p>

<p><strong>Association rules:</strong> "Access violation" error was corrected. It occurred if large data sets were supplied to both node inputs, nodes were configured (elements and transactions were set) and then the node training process was started and terminated (#10094).</p>

<p><a href="https://help.loginom.ru/userguide/visualization/data-quality/" target="_blank"><strong>Data quality visualizer:</strong></a> The following error was corrected: "Cannot read properties of undefined (reading 'isGroupHeader')". It occurred when activating <em>Data quality</em> visualizer from the <em>Reports</em> page without prior entering the visualizer from the&nbsp;<em>Visualizers</em> page (#9470).</p>

<p><a href="https://help.loginom.ru/userguide/visualization/table/" target="_blank"><strong>Визуализатор Таблица:</strong></a> Исправлена ошибка «Набор данных не находится в закрытом состоянии», которая возникала, если в таблице с большим количеством колонок (~200) настроить сортировку по ~20 столбцам, быстро перейти в сценарий, открытый на соседней вкладке, и деактивировать узел, на котором настроен визуализатор (#9963).</p>

<p><strong>Table visualizer:</strong> Auto selection of the column width by the header text didn't work for some columns due to rounding and difference in 1 pixel. The problem is typical of somebrowsers (for example, Chrome). Corrections were introduced.</p>

<p><a href="https://help.loginom.ru/userguide/processors/transformation/grouping.html" target="_blank"><strong>Grouping</strong></a>, <a href="https://help.loginom.ru/userguide/processors/variables/variables-from-table.html" target="_blank"><strong>Table to variables:</strong></a> For the columns that relate to the integer type and contain the values that are more than 2<sup>53</sup> - 1 or less than -2<sup>53</sup> + 1, errors can occur in aggregations: <em>Minimum, Maximum, Mode, First, Last, Single</em>. When calculating the unique values count, different unique values could be counted as one. The required corrections were introduced, indicators are calculated without loss of accuracy (#9943).</p>

<p><a href="https://help.loginom.ru/userguide/integration/import/ldf.html" target="_blank"><strong>Import from LGD:</strong></a> If the output fields were deleted for the data set with one column in the output port, the field related to the<em>Variable</em> type was added and they were connected afterwards, the following error occurred when starting the node: "Metadata does not comply with the previously declared metadata" (#8426).</p>

<p><strong>Импорт из LGD:</strong>&nbsp;When connecting the fields related to different types with the field related to the <em>Variable</em> type, the following error could occur: "Unsupported Variant subtype" (#8427).</p>

<p><a href="https://help.loginom.ru/userguide/processors/preprocessing/coarse-classes.html" target="_blank"><strong>Конечные классы:</strong></a> Открытие в браузере страницы мастера настройки узла <em>Конечные классы</em> по ссылке, полученной по кнопке Поделиться, приводило к ошибке: «При переходе на "Конечные классы. Настройка" возникла ошибка. Cannot read properties of undefined (reading 'PrepareFilterField')». The error was corrected.</p>

<p><strong>Logging:</strong> Screening of the string parameters values was added for the log parts that are recorded in JSON format (parameters). Now the parameters related to the <code>Boolean</code> type instead of <code>True</code> and <code>False</code> are recorded as <code>true</code>and <code>false</code>.</p>

<p><strong>Desktop application:</strong> The following problems were solved: incorrect display of the application window when the desktop Loginom edition with two display monitors was used, namely:</p>

<ul>
	<li>when dragging the application window from one screen (the larger one) to another one, a part of the window was covered with the gray panel (#9024);</li>
	<li>when dragging the application window from the larger screen (~4К) to the smaller one, the window didn't change the scale automatically (#9091);</li>
	<li>if the application was deployed two times to full screen using Win+Up keys on the left screen, a part of the window was displayed on the right screen (when using one screen, a part of the window was under the Taskbar(#8296).</li>
</ul>

<p><strong>Desktop application:</strong> When opening any package (to open using Loginom) or just when starting Loginom CE, the application window was opened but the interface was not displayed. It was possible to close this Loginom CE window only using the Sesson Manager. The repeated application launch was successful. The problem of the first launch was solved (#9720).</p>

<p><a href="https://help.loginom.ru/userguide/processors/datamining/neural-network-classification.html" target="_blank"><strong>Neural network (Classification):</strong></a> "Not trained neural network" error was corrected. It occurred in the <em>Neural network (Classification)</em> node, the layers configuration of which was set using the control variables. The error could occur after repeated opening of the package and activation of the trained neural network, and also if the clone of such neural network was activated (#10137).</p>

<p><strong>Workflow construction area:</strong> After cancellation of the process executed for a long time via <a href="https://help.loginom.ru/userguide/interface/processes-panel.html" target="_blank">Processes Bar</a> (for example, JavaScript node with the loop equal to 100,000,000 iterations), the node activation animation was preserved in the workflow construction area, some interface elements were not available. The error was corrected (#6246).</p>

<p><strong>Workflow construction area:</strong> The cloned node appeared far from the source one if the source node was located far from the left upper corner of the workflow construction area. The further the node was located from the left upper corner of the workflow construction area, the futher the cloned node appeared from it. Error of behavior was corrected (#4908).</p>

<p><strong>Workflow construction area:</strong> If the scale was changed using the "Workflow map" function, the node was added to the workflow construction area in the right lower corner, then the package was saved and closed, and the coordinates of the added node were incorrect after saving the package in 100% scale. The node was located in the lower corner of the visible workflow part. But it was to be located in the same place where it was added when changing the scale. The error of coordinates saving was corrected (#10097).</p>

<p><a href="https://help.loginom.ru/userguide/integration/connections/" target="_blank"><strong>Подключение к базе данных:</strong></a> Исправлена ошибка "Login failed for user...", которая возникала после открытия пакета с ранее настроенным подключением к базе данных с паролем более 32 символов, при активации или тестировании подключения. При сохранении пакета пароль урезался до 32 байт и, как следствие, после повторного открытия пакета подключение к базе данных не работало (#9462).</p>

<p><strong>Подключение к базе данных:</strong> При разорванном соединении базы данных с сервером запуск на выполнение узла&nbsp;<em>Импорт из базы данных</em> завершался отменой выполнения узла, т.е. узел не выполнялся, а пользователь не получал никаких сообщений. The situation was rectified. Upon database server connection loss, <em>Import from database</em> node execution was finished with an error message (#10049).</p>

<p><a href="https://help.loginom.ru/userguide/integration/connections/list/schemes.html" target="_blank"><strong>Подключение набора XSD-схем:</strong></a> Исправлена ошибка "List index out of bounds", которая возникала в мастере <em>Настройка набора XSD-схем</em> при добавлении в список двух схем и их поочередного удаления (#9522).</p>

<p><a href="https://help.loginom.ru/userguide/processors/control/supernode.html" target="_blank"><strong>Supernode:</strong></a> When adding 5 or more input or output ports to the supernode and selecting the port type, after saving it was not possible to change the type of any of the previously added ports. The error was corrected (#10123).</p>

<p><strong>Приложение:</strong> В визуализаторе <em>Таблица</em>, в <a href="https://help.loginom.ru/userguide/interface/property-inspector.html" target="_blank">Инспекторе свойств</a> и в <em>Диспетчере</em> можно было столкнуться с ситуацией, когда при клике правой кнопкой мыши в таблице не выделялась ячейка, а контекстное меню отображало пункты для предыдущей выделенной ячейки. Error of behavior was corrected (#8104).</p>

<p><strong>Application:</strong> "Cannot read property 'NodeIndex' of null" error was corrected. It occurred if the user only with the administration rights opened the package from the file storage. Now, in this case the explanatory message is displayed (#6787).</p>

<p><strong>Application:</strong> The pop-up tip was not hidden in the wizards for the link for which there was no field. Такая ситуация могла возникнуть, например, если в узле <em>Квантование</em> поданы данные на второй входной порт, в мастере настройки для любого входного поля установлена связь с назначением, далее поля или назначения отфильтрованы так, что связанное поле не попало под условие фильтрации (скрылось). The tip previously displayed for connection was not hidden. Error of behavior was corrected (#9955).</p>

<p><strong>Приложение:</strong> В редакторе ввода значений типа Дата/время (используется, например, в узле <a href="https://help.loginom.ru/userguide/processors/transformation/row-filter/" target="_blank">Фильтр строк</a>) не локализовался первый день недели и текст кнопки установки текущей даты (в русскоязычной и англоязычной версиях кнопка называлась Current Date). The error was corrected (#10096).</p>

<p><strong>"Connections" page:</strong> "Cannot read property 'getStore' of undefined" error was corrected. It occurred if <em>"Connections" page</em> was closed while testing the connection being activated for a long time (#8763).</p>

<p><a href="https://help.loginom.ru/userguide/processors/control/condition.html" target="_blank"><strong>Условие:</strong></a> В мастере настройки кнопки&nbsp;<em>Переместить вверх</em> и <em>Переместить вниз</em> были доступны при отсутствии портов (если сразу после добавления узла в область построения сценария открыть мастер настройки). Error of behavior was corrected. If there is nothing to move, the buttons are not available (#10013).</p>

<p><strong>Условие:</strong> Если на странице мастера настройки «Настройка списка портов» задать 2 порта, а затем второй порт переместить вверх, то нарушается нумерация портов (строк в таблице содержащей список портов) — оба порта имели номер 2. The error was corrected (#10014).</p>

<p><a href="https://help.loginom.ru/userguide/integration/export/excel.html" target="_blank"><strong>Export to Excel file:</strong></a> "Sheet name not set" error was corrected. It occurred in the Export to Excel file wizard when using the variable as the value of the <em>Sheet name</em> parameter after clicking on <em>Next</em> button at the first wizard step (#10081).</p>

<p><a href="https://help.loginom.ru/userguide/integration/export/ldf.html" target="_blank"><strong>Экспорт в LGD-файл:</strong></a> Если при длительном выполнении экспорта в LGD-файл останавливалось выполнение узла (нажатием на узел), то узел все равно переходил в состояние «Выполнен успешно». It is a regression error and it appeared in version 7.0.0. Внесли исправления: узел экспорта, выполнение которого остановлено, остается серым, а в <em>Панели процессов</em> указывается, что обработка прервана (#10028).</p>

<p><strong>Экспорт в LGD-файл:</strong> Когда <em>Экспорт</em>&nbsp;происходил из <em>Импорта LGD, TXT, Excel</em> или из <em>Цикла</em>, при перестановке местами полей, содержащих null-значения, поля экспортировались неправильно: вместо null-значений появлялся false, 0, 0.00, 00:00 или пустые строки, в зависимости от типа; вместо ненулевых значений — null-значения. The error was corrected (#9896).</p>

<p><strong>Export to LGD file:</strong> "Access violation" error was corrected. It occurred when activating the node in the input port of which all fields were deleted with the exception of the field related to the variable type (or the field related to the variable type was moved to another position in the list). In this case, the input data set came from&nbsp;<em>LGD, TXT, Excel import</em> or from <em>Loop</em> nodes (#9612).</p>

<div class="text-align-center">
<p class="lg-text-btn lg-text-btn_border"><a href="https://loginom.ru/download">Try new version</a></p>
</div>
